### ISSUE TITLE
Stress testing on the Pi

### ISSUE THREAD

**Issue by rahulsanjay18** [rahulsanjay18/3dGraph#24]
Give the number of blocks that the Pi can generate in around half a second.

**Comment by schuler001** [comment]
Stress testing isn't complete yet, but preliminary tests show it can easily render 32^4 blocks streamed through VNC within one half second

**Comment by schuler001** [comment]
I would say the cap is about 50. Trying 75 was loaded but it took a noticeable (about 1.5 seconds) time to load
